name: Run pip-audit
description: Setup python and run pip-audit

inputs:
  working-directory:
    required: false
    description: Repository to work on
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5
    with:
      enable-cache: true
      cache-suffix: audit
      cache-dependency-glob: ${{ inputs.working-directory }}/pyproject.toml

  - name: Check dependencies
    run: |
      uvx pip-compile --output-file=requirements.txt pyproject.toml
      uvx pip-audit -r requirements.txt
    shell: bash
    working-directory: ${{ inputs.working-directory }}
