name: Run pip-audit
description: Setup python and run pip-audit

inputs:
  working-directory:
    required: false
    description: Repository to work on
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
    with:
      version: ${{ env.UV_VERSION }}
      enable-cache: true
      cache-suffix: audit
      cache-dependency-glob: ${{ inputs.working-directory }}/pyproject.toml
    env:
      # renovate: datasource=github-releases depName=astral-sh/uv
      UV_VERSION: 0.9.28

  - name: Check dependencies
    run: |
      uvx pip-compile --output-file=requirements.txt pyproject.toml
      uvx pip-audit -r requirements.txt
    shell: bash
    working-directory: ${{ inputs.working-directory }}
