name: Run pip-audit
description: Setup python and run pip-audit

inputs:
  working-directory:
    required: false
    description: Repository to work on
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Set up Python
    uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
    with:
      cache: pip
      cache-dependency-path: ${{ inputs.working-directory }}/pyproject.toml

  - name: Check dependencies
    run: |
      pip install -q pip-compile pip-audit
      pip-compile --output-file=requirements.txt pyproject.toml
      pip-audit -r requirements.txt
    shell: bash
    working-directory: ${{ inputs.working-directory }}
