name: Create issue
description: Creates issue with given content

inputs:
  github-token:
    required: true
    description: Github token
  title:
    required: true
    description: Issue title
  body:
    required: true
    description: Issue body
  label:
    required: false
    description: Issue label
    default: ''
outputs:
  issue-url:
    description: URL of the created issue
    value: ${{ steps.script.outputs.url }}
  issue-id:
    description: ID of the created issue
    value: ${{ steps.script.outputs.number }}

runs:
  using: composite
  steps:
  - id: script
    uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea   # v7
    env:
      LABEL: ${{ inputs.label }}
      TITEL: ${{ inputs.title }}
      BODY: ${{ inputs.body }}
    with:
      github-token: ${{ inputs.github-token }}
      script: |
        const { owner, repo, } = context.repo
        const { LABEL, TITEL, BODY } = process.env
        const labels = LABEL ? [LABEL] : []

        const { url, number } = await github.rest.issues.create({
          owner,
          repo,
          title: TITEL,
          body: BODY,
          labels,
          assignees: [],
        });

        core.setOutput('url', url);
        core.setOutput('number', number);
        core.info('Created issue: ' + url)
