name: Create pull request
description: Creates pull request from branch against main branch

inputs:
  github-token:
    required: true
    description: Github token
  title:
    required: true
    description: Pull request title
  branch:
    required: true
    description: Branch to create pull request from
  reviewer:
    required: false
    description: Reviewer to add to the pull request
    default: ''
outputs: {}

runs:
  using: composite
  steps:
  - name: Create pull request
    run: |
      if [ -n "${{ inputs.reviewer }}" ]; then
        gh pr create --title "${{ inputs.title }}" --head "${{ inputs.branch }}"
      else
        gh pr create --title "${{ inputs.title }}" --head "${{ inputs.branch }}" --reviewer "${{ inputs.reviewer }}"
      fi
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
