name: Create release for tag
description: Creates new release for existing tag

inputs:
  github-token:
    required: true
    description: Github token
  tag-name:
    required: true
    description: Already existing tag that should be released
outputs: {}

runs:
  using: composite
  steps:
  - uses: actions/github-script@v5.1.0
    with:
      github-token: ${{ inputs.github-token }}
      script: |
        const repository = context.repo
        await github.rest.repos.createRelease({
          owner: repository.owner,
          repo: repository.repo,
          tag_name: '${{ inputs.tag-name }}',
        });
