name: Run black
description: Setup python and run black

inputs:
  working-directory:
    required: false
    description: Repository to work on
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@f3bcaebff5eace81a1c062af9f9011aae482ca9d # v3
    with:
      enable-cache: true
      cache-suffix: black

  - name: Run black
    run: uvx black .
    shell: bash
    working-directory: ${{ inputs.working-directory }}
