name: Run black
description: Setup python and run black

inputs:
  working-directory:
    required: false
    description: Repository to work on
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Set up Python
    uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
    with:
      cache: pip

  - name: Run black
    run: |
      pip install -q black
      black .
    shell: bash
    working-directory: ${{ inputs.working-directory }}
