name: Setup pre-commit
description: Setup pre-commit with caching

inputs:
  python-version:
    required: false
    description: Python version
    default: 3.x
  working-directory:
    required: false
    description: Repository to run pre-commit in
    default: .
outputs:
  update_log:
    description: Log lines with updated pre-commit repositories, if any
    value: ${{ steps.autoupdate.outputs.UPDATES }}

runs:
  using: composite
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: ${{ inputs.working-directory }}/.pre-commit-config.yaml

  - name: Cache pre-commit
    uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
    with:
      path: ~/.cache/pre-commit
      key: ${{ runner.os }}-pre-commit-${{ inputs.python-version }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

  - name: Install pre-commit
    run: pip install -q pre-commit
    shell: bash
