name: Setup python with pip cache
description: Setup python pip cache with cache key

inputs:
  python-version:
    required: false
    description: Python version
    default: 3.x
  working-directory:
    required: false
    description: Repository to build from
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: |
        ${{ inputs.working-directory }}/setup.cfg
        ${{ inputs.working-directory }}/pyproject.toml

  - name: Upgrade pip
    run: python -m pip install -q --upgrade pip
    shell: bash
