name: Setup python with pip cache
description: Setup python pip cache with cache key

inputs:
  python-version:
    required: false
    description: Python version
    default: '3.10'
outputs: {}

runs:
  using: composite
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v3.0.0
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: setup.cfg

  - name: Upgrade pip
    run: python -m pip install -q --upgrade pip
    shell: bash
