name: Setup python with pip cache
description: Setup python pip cache with cache key

inputs:
  python-version:
    required: false
    description: Python version
    default: 3.x
  working-directory:
    required: false
    description: Repository to build from
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: |
        ${{ inputs.working-directory }}/setup.cfg
        ${{ inputs.working-directory }}/pyproject.toml

  - name: Upgrade pip
    run: python -m pip install -q --upgrade pip
    shell: bash
