name: Update pre-commit config
description: Update pre-commit configuration and test it still works

inputs:
  python-version:
    required: false
    description: Python version
    default: '3.11'
  working-directory:
    required: false
    description: Repository to run pre-commit in
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: ${{ inputs.working-directory }}/.pre-commit-config.yaml

  - name: Cache pre-commit
    uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: ${{ runner.os }}-pre-commit-${{ inputs.python-version }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

  - name: Update pre-commit
    run: |
      echo "::warning use action boidolr/run-precommit with option autoupdate=true instead"
      pip install -q pre-commit
      pre-commit autoupdate
      pre-commit run --all-files
    shell: bash
    working-directory: ${{ inputs.working-directory }}
