name: Setup python with poetry cache
description: Setup python and poetry with venv caching

inputs:
  python-version:
    required: false
    description: Python version
    default: 3.x
  working-directory:
    required: false
    description: Repository to build from
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Install poetry
    run: pipx install poetry
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
    with:
      python-version: ${{ inputs.python-version }}
      cache: poetry
      cache-dependency-path: ${{ inputs.working-directory }}/pyproject.toml
