name: Run pre-commit
description: Run pre-commit with configuration and test it still works

inputs:
  python-version:
    required: false
    description: Python version
    default: '3.11'
  autoupdate:
    required: false
    description: Run autoupdate for configured pre-commit hooks
    default: false
  working-directory:
    required: false
    description: Repository to run pre-commit in
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: ${{ inputs.working-directory }}/.pre-commit-config.yaml

  - name: Cache pre-commit
    uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: ${{ runner.os }}-pre-commit-${{ inputs.python-version }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

  - name: Install pre-commit
    run: pip install -q pre-commit
    shell: bash
    working-directory: ${{ inputs.working-directory }}

  - name: Run pre-commit autoupdate
    if: ${{ inputs.autoupdate }}
    run: pre-commit autoupdate
    shell: bash
    working-directory: ${{ inputs.working-directory }}

  - name: Run pre-commit
    run: pre-commit run --all-files
    shell: bash
    working-directory: ${{ inputs.working-directory }}
