name: Run pre-commit
description: Run pre-commit with configuration and test it still works

inputs:
  autoupdate:
    required: false
    description: Run autoupdate for configured pre-commit hooks
    default: 'false'
  working-directory:
    required: false
    description: Repository to run pre-commit in
    default: .
outputs:
  update_log:
    description: Log lines with updated pre-commit repositories, if any
    value: ${{ steps.autoupdate.outputs.UPDATES }}

runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6
    with:
      version: ${{ env.UV_VERSION }}
      enable-cache: true
      cache-suffix: precommit
      cache-dependency-glob: ${{ inputs.working-directory }}/.pre-commit-config.yaml
    env:
      # renovate: datasource=github-releases depName=astral-sh/uv
      UV_VERSION: 0.7.9

  - name: Cache pre-commit
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
    with:
      path: ~/.cache/pre-commit
      key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

  - name: Run pre-commit autoupdate
    id: autoupdate
    if: ${{ inputs.autoupdate == 'true' }}
    run: |
      logs=$(uvx --with pre-commit-uv pre-commit autoupdate | grep updating || echo '')
      if [ -n "$logs" ]; then
        echo "UPDATES<<EOF" >> $GITHUB_OUTPUT
        echo "${logs}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      fi
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      UV_PYTHON_PREFERENCE: only-managed

  - name: Run pre-commit
    run: uvx --with pre-commit-uv pre-commit run --show-diff-on-failure --all-files
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      UV_PYTHON_PREFERENCE: only-managed
