name: Sync with upstream
description: Fetch upstream, fast forward merge and push changes

inputs:
  github-token:
    required: true
    description: Github token
  branch:
    required: false
    description: Branch to sync - needs to match upstream branch
    default: main
  repo:
    required: false
    description: Repo to sync ('owner/repo')
  working-directory:
    required: false
    description: Repository to work on
    default: .
outputs: {}

runs:
  using: composite
  steps:
  - run: |
      gh repo sync --branch '${{ inputs.branch }}' '${{ inputs.repo }}'
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
