name: Setup git user and push changes
description: Setup git user and push changes

inputs:
  branch:
    required: true
    description: Branch to push
  message:
    required: true
    description: Commit message
  working-directory:
    required: false
    description: Repository to push changes from
    default: .
  user-name:
    required: false
    description: Git user name
    default: github-actions
  user-email:
    required: false
    description: Git user email
    default: 41898282+github-actions[bot]@users.noreply.github.com
outputs:
  pushed-changes:
    description: '`true` if changes were pushed, `false` otherwise'
    value: ${{ steps.git-push-changes.outputs.updated }}

runs:
  using: composite
  steps:
  - uses: actions/github-script@v6
    id: git-push-changes
    with:
      script: |
        const CWD = '${{ inputs.working-directory }}';
        const diff = await exec.exec(
            'git', ['-C', CWD, 'diff', '--quiet'], { ignoreReturnCode: true, }
        );
        core.setOutput('updated', `${!!diff}`);

        if (diff) {
          await exec.exec('git', ['-C', CWD, 'config', 'user.name', '${{ inputs.user-name }}']);
          await exec.exec('git', ['-C', CWD, 'config', 'user.email', '${{ inputs.user-email }}']);
          await exec.exec('git', ['-C', CWD, 'commit', '-am', `${{ inputs.message }}`]);
          await exec.exec('git', ['-C', CWD, 'push', 'origin', 'HEAD:${{ inputs.branch }}']);
        }
