name: Setup git user and push changes
description: Setup git user and push changes

inputs:
  branch:
    required: true
    description: Branch to push
  message:
    required: true
    description: Commit message
  working-directory:
    required: false
    description: Repository to push changes from
    default: .
  user-name:
    required: false
    description: Git user name
    default: ''
  user-email:
    required: false
    description: Git user email
    default: ''
outputs:
  pushed-changes:
    description: '`true` if changes were pushed, `false` otherwise'
    value: ${{ steps.git-push-changes.outputs.updated }}

runs:
  using: composite
  steps:
  - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b   # v7
    id: git-push-changes
    env:
      CWD: ${{ inputs.working-directory }}
      MESSAGE: ${{ inputs.message }}
      BRANCH: ${{ inputs.branch }}
      NAME: ${{ inputs.user-name || github.actor }}
      EMAIL: ${{ inputs.user-email || format('{0}@users.noreply.github.com', github.actor) }}
    with:
      script: |
        const { CWD, MESSAGE, BRANCH, NAME, EMAIL } = process.env;
        const diff = await exec.exec(
            'git', ['-C', CWD, 'diff', '--quiet'], { ignoreReturnCode: true, }
        );
        core.setOutput('updated', `${!!diff}`);

        if (diff) {
            await exec.exec('git', ['-C', CWD, 'config', 'user.name', NAME]);
            await exec.exec('git', ['-C', CWD, 'config', 'user.email', EMAIL]);
            await exec.exec('git', ['-C', CWD, 'commit', '-am', MESSAGE]);
            await exec.exec('git', ['-C', CWD, 'push', 'origin', `HEAD:${BRANCH}`]);
        }
