name: Renovate check
on:
  pull_request:
    paths:
    - presets/**
    - default.json
    - renovate.json

  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1         # v7.0.1
      with:
        persist-credentials: false

    - name: Install node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020         # v7.0.0
      with:
        node-version: 24
        cache: npm
        cache-dependency-path: |
          presets/**
          default.json
          renovate.json

    - name: Check renovate config
      run: npx --yes --package renovate -- renovate-config-validator --strict default.json renovate.json presets/**

    - name: Renovate dry-run
      run: npx --yes --package renovate -- renovate --dry-run --autodiscover
      env:
        RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RENOVATE_USE_BASE_BRANCH_CONFIG: ${{ github.ref }}
