name: pre-commit update

on:
  workflow_call:
    inputs:
      branch:
        required: false
        default: main
        type: string

permissions:
  contents: write

jobs:
  pre-commit-update:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803         # v6

    - uses: boidolr/actions/run-precommit@d87fde10d5386f84f4ac1cd9b6becb61b7b892fe # main
      id: precommit
      with:
        autoupdate: true

    - name: Push pre-commit changes
      uses: boidolr/actions/git-push@d87fde10d5386f84f4ac1cd9b6becb61b7b892fe # main
      if: ${{ steps.precommit.outputs.update_log }}
      with:
        message: |
          chore: update pre-commit config


          ${{ steps.precommit.outputs.update_log }}
        branch: ${{ inputs.branch }}
