name: pre-commit update

on:
  workflow_call:
    inputs:
      branch:
        required: false
        default: main
        type: string

permissions:
  contents: write

jobs:
  pre-commit-update:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1         # v7.0.1

    - uses: boidolr/actions/run-precommit@47f62c14dbb70a62193d06271aa77c67ef110445 # main
      id: precommit
      with:
        autoupdate: true

    - name: Push pre-commit changes
      uses: boidolr/actions/git-push@47f62c14dbb70a62193d06271aa77c67ef110445 # main
      if: ${{ steps.precommit.outputs.update_log }}
      with:
        message: |
          chore: update pre-commit config


          ${{ steps.precommit.outputs.update_log }}
        branch: ${{ inputs.branch }}
