name: pre-commit update
on:
  workflow_dispatch:
  schedule:
  - cron: 13 7 */7 * *

permissions:
  contents: write

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    env:
      BRANCH: main

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Update pre-commit
      uses: boidolr/actions/run-precommit@main
      with:
        autoupdate: true

    - name: Push pre-commit changes
      uses: boidolr/actions/git-push@main
      with:
        message: Update pre-commit config
        branch: ${{ env.BRANCH }}
